export { default as Navbar } from './Navbar/Navbar';
export { default as Section } from './Section/MainPage/Section';
export { default as WelcomeContainer } from './Section/MainPage/WelcomeFooter';
export { default as Footer } from './Footer/Footer';
export { default as AnotherPage } from './Section/AnotherPage/AnotherPage';
export { default as FormButton } from './FormButton/FormButton';
export { default as MainPannel } from './ChatPannel/MainPannel/MainPannel';
export { default as HeaderPannel } from './ChatPannel/HeaderPannel/HeaderPannel';
export { default as SidePannel } from './ChatPannel/SidePannel/SidePannel/SidePannel';
